### ISSUE TITLE
My session gets closed on my Ubuntu desktop

### ISSUE THREAD

**Issue by alauzon** [geerlingguy/drupal-jenkins-multisite#13]
I have some other docker that is using port 443.  So before doing 'docker-compose up -d' I have to stop another docker that is using the same 443 port.

Once that is done I can do 'docker-compose up -d'.

10 seconds after that my graphical session on my Ubuntu 18.04 closes and asks me to enter my password again to reopen the graphical session.  If i put my password in there it does nothing.  If I wait a little bit everything is blocked.  My mouse does not move and I can't login.

What can cause that?

**Comment by alauzon** [comment]
Now I have switched from gdm3 to lightdm and the problem stopped.

**Comment by geerlingguy** [comment]
Closing this per https://github.com/geerlingguy/drupal-jenkins-multisite/issues/15
