### ISSUE TITLE
Note to install roles

### ISSUE THREAD

**Issue by mglaman** [geerlingguy/drupal-jenkins-multisite#4]
I got ahead of myself and went to deploy and forgot to install the roles :) 

Adding the install command will really help those who may be Ansible novices.

```
$ ansible-galaxy install -r requirements.yml 
```

**Comment by geerlingguy** [comment]
Oops! I'm guessing you mean prior to running the playbook, in the 'Production Setup' section of the README? If so, yeah that should be a separate step.

**Comment by mglaman** [comment]
@geerlingguy which I totally skipped the local setup which would have done that. So I guess it is technically correct.

**Comment by geerlingguy** [comment]
Actually you're correct that this step is missed in the "Production Setup" section. I'm going to update that now.
