### ISSUE TITLE
Automated Jenkins job installation via Ansible role

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-jenkins-multisite#7]
Not too long ago I set out to automate the installation/management of Jenkins jobs.

It has been a problem I've been facing for some time, but I finally have an elegant solution.

I thought I'd raise this to you @geerlingguy, as you may be interested in the idea - if you wanted to recreate or use it...
* https://github.com/fubarhouse/ansible-role-jenkins-jobs

**Comment by geerlingguy** [comment]
Thanks! I'll take a look for sure. So far I've been mostly relying on the `copy` module and grabbing jobs off the server directly, but anything more streamlined is welcome.

**Comment by Gabelbombe** [comment]
+1 to getting this integrated

**Comment by geerlingguy** [comment]
Closing this per https://github.com/geerlingguy/drupal-jenkins-multisite/issues/15
