### ISSUE TITLE
Question - Resources for servers

### ISSUE THREAD

**Issue by MsGenaThompson** [geerlingguy/drupal-jenkins-multisite#9]
We've been using AEGIR for our multisite environment (18 Drupal 7 subsites) and are interested in attempting to use Jenkins for our automation of our multisite environment in future. We will be starting of with one subsite and I was wondering if you could give me an indication of the resources that we would need for the jenkins and site servers. (The current app files is 3.5 Gig and the database is 332MB.

**Comment by geerlingguy** [comment]
I would start with a server with at least 1 or preferably 2 GB of RAM, and probably at least 20 GB of disk space (in case you need to do operations on the database and/or codebase which could take a few GB per job run). CPU is usually not a bottleneck, so focus on getting as much RAM and disk space as you can first.
